<?php
use Facebook\Facebook\Filter\ControlLengthResults;
?>
<div class="content">
<?php
 $title = "Spis Postów do Facebooka";
 $this->headTitle($title);
?>
<div class="title">
 <h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>message</th>
        </tr>
        <?php  foreach($messages as $message) : ?>
            <tr>
                <?php
                  $filter = new ControlLengthResults();
                ?>
                <td class="id_label"><?php echo $this->escapeHtml($message['id']); ?></td>
                <td class="message_label"><?php echo $filter->showFetchResults($this->escapeHtml($message['message'])); ?></td>
                <td class="nav_label">
                    <a href="<?php echo $this->url('delete', array('action' => 'delete', 'id' => $message['id'])); ?>"><button>Delete</button></a> ||
                    <a href="<?php echo $this->url('edit', array('action' => 'edit', 'id' => $message['id'])); ?>"><button>Edit</button></a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
</div>
